package gosms

const (
	CC_GLOBAL  = 0    // 如果不存在该国的短信sdk,则默认使用这个全球发送
	CC_CP     = 011  // Clipperton Island | 克利珀顿岛
	CC_KY     = 1345 // Cayman Islands | 开曼群岛
	CC_YT     = 262  // Mayotte | 马约特
	CC_CO     = 57   // Colombia | 哥伦比亚
	CC_KP     = 850  // North Korea | 朝鲜
	CC_LV     = 371  // Latvia | 拉脱维亚
	CC_SV     = 503  // El Salvador | 萨尔瓦多
	CC_BA     = 387  // Bosnia & Herzegovina | 波黑
	CC_GL     = 299  // Greenland | 格陵兰
	CC_MT     = 356  // Malta | 马耳他
	CC_UZ     = 998  // Uzbekistan | 乌兹别克斯坦
	CC_AM     = 374  // Armenia | 亚美尼亚
	CC_AX     = 358  // Åland Islands | 奥兰群岛
	CC_MK     = 389  // Macedonia | 北马其顿共和国
	CC_CV     = 238  // Cape Verde | 佛得角
	CC_GT     = 502  // Guatemala | 危地马拉
	CC_LI     = 423  // Liechtenstein | 列支敦士登
	CC_TL     = 670  // Timor-Leste | 东帝汶
	CC_MG     = 261  // Madagascar | 马达加斯加
	CC_NZ     = 64   // New Zealand | 新西兰
	CC_ZW     = 263  // Zimbabwe | 津巴布韦
	CC_HM     = 672  // Heard And McDonald Islands | 赫德岛和麦克唐纳群岛
	CC_NE     = 227  // Niger | 尼日尔
	CC_PN     = 64   // Pitcairn Islands | 皮特凯恩群岛
	CC_SY     = 963  // Syria | 叙利亚
	CC_VU     = 678  // Vanuatu | 瓦努阿图
	CC_WS     = 685  // Samoa | 萨摩亚
	CC_TR     = 90   // Turkey | 土耳其
	CC_VC     = 1784 // St. Vincent & Grenadines | 圣文森特和格林纳丁斯
	CC_CW     = 599  // Curaçao | 库拉索
	CC_GQ     = 240  // Equatorial Guinea | 赤道几内亚
	CC_IQ     = 964  // Iraq | 伊拉克
	CC_KM     = 269  // Comoros | 科摩罗
	CC_SB     = 677  // Solomon Islands | 所罗门群岛
	CC_TK     = 690  // Tokelau | 托克劳
	CC_KR     = 82   // South Korea | 南非
	CC_UY     = 598  // Uruguay | 乌拉圭
	CC_RE     = 262  // Réunion | 留尼汪
	CC_BY     = 375  // Belarus | 白俄罗斯
	CC_CL     = 56   // Chile | 智利
	CC_DG     = 246  // Diego Garcia | 迪戈加西亚岛
	CC_ET     = 251  // Ethiopia | 埃塞俄比亚
	CC_HT     = 509  // Haiti | 海地
	CC_IT     = 39   // Italy | 意大利
	CC_AQ     = 672  // Antarctica | 南极洲
	CC_LB     = 961  // Lebanon | 黎巴嫩
	CC_LS     = 266  // Lesotho | 莱索托
	CC_TM     = 993  // Turkmenistan | 土库曼斯坦
	CC_TV     = 688  // Tuvalu | 图瓦卢
	CC_BB     = 1246 // Barbados | 巴巴多斯
	CC_CI     = 225  // Côte d’Ivoire | 科特迪瓦
	CC_ER     = 291  // Eritrea | 厄立特里亚
	CC_HN     = 504  // Honduras | 洪都拉斯
	CC_IS     = 354  // Iceland | 冰岛
	CC_KH     = 855  // Cambodia | 柬埔寨
	CC_AL     = 355  // Albania | 阿尔巴尼亚
	CC_CR     = 506  // Costa Rica | 哥斯达黎加
	CC_DZ     = 213  // Algeria | 阿尔及利亚
	CC_MD     = 373  // Moldova | 摩尔多瓦
	CC_BN     = 673  // Brunei | 文莱
	CC_FK     = 500  // Falkland Islands | 福克兰群岛（马尔维纳斯）
	CC_GA     = 241  // Gabon | 加蓬
	CC_GU     = 1671 // Guam | 关岛
	CC_TD     = 235  // Chad | 乍得
	CC_AF     = 93   // Afghanistan | 阿富汗
	CC_CF     = 236  // Central African Republic | 中非
	CC_DM     = 1767 // Dominica | 多米尼克
	CC_IO     = 246  // British Indian Ocean Territory | 英属维尔京群岛
	CC_OM     = 968  // Oman | 阿曼
	CC_SK     = 421  // Slovakia | 斯洛伐克
	CC_BQ     = 599  // Caribbean Netherlands | 库拉索
	CC_LK     = 94   // Sri Lanka | 斯里兰卡
	CC_LU     = 352  // Luxembourg | 卢森堡
	CC_PL     = 48   // Poland | 波兰
	CC_IE     = 353  // Ireland | 爱尔兰
	CC_MV     = 960  // Maldives | 马尔代夫
	CC_QA     = 974  // Qatar | 卡塔尔
	CC_MH     = 692  // Marshall Islands | 马绍尔群岛
	CC_TZ     = 255  // Tanzania | 坦桑尼亚
	CC_GH     = 233  // Ghana | 加纳
	CC_NP     = 977  // Nepal | 尼泊尔
	CC_TJ     = 992  // Tajikistan | 塔吉克斯坦
	CC_XK     = 383  // Kosovo | 科索沃
	CC_AU     = 61   // Australia | 澳大利亚
	CC_DJ     = 253  // Djibouti | 吉布提
	CC_JP     = 81   // Japan | 日本
	CC_PY     = 595  // Paraguay | 巴拉圭
	CC_RU     = 7    // Russia | 俄罗斯
	CC_SD     = 249  // Sudan | 苏丹
	CC_BS     = 1242 // Bahamas | 巴哈马国
	CC_FR     = 33   // France | 法国
	CC_SE     = 46   // Sweden | 瑞典
	CC_TA     = 290  // Tristan da Cunha | 特里斯坦-达库尼亚群岛
	CC_MY     = 60   // Malaysia | 马来西亚
	CC_TC     = 1649 // Turks & Caicos Islands | 特克斯和凯科斯群岛
	CC_CU     = 53   // Cuba | 古巴
	CC_FM     = 691  // Micronesia | 密克罗尼西亚联邦
	CC_GI     = 350  // Gibraltar | 直布罗陀
	CC_KI     = 686  // Kiribati | 基里巴斯
	CC_PS     = 970  // Palestinian Territories | 巴勒斯坦地区
	CC_TH     = 66   // Thailand | 泰国
	CC_BE     = 32   // Belgium | 比利时
	CC_CM     = 237  // Cameroon | 喀麦隆
	CC_EA     = 34   // Ceuta And Melilla | 休塔和梅利拉
	CC_JE     = 44   // Jersey | 泽西岛
	CC_NI     = 505  // Nicaragua | 尼加拉瓜
	CC_AW     = 297  // Aruba | 阿鲁巴
	CC_AS     = 1684 // American Samoa | 美属萨摩亚
	CC_CG     = 242  // Congo - Brazzaville | 刚果（布）
	CC_GB     = 44   // United Kingdom | 英国
	CC_LY     = 218  // Libya | 利比亚
	CC_JO     = 962  // Jordan | 约旦
	CC_NA     = 264  // Namibia | 纳米尼亚
	CC_PA     = 507  // Panama | 巴拿马
	CC_RS     = 381  // Serbia | 塞尔维亚和黑山
	CC_SA     = 966  // Saudi Arabia | 沙特阿拉伯
	CC_SJ     = 47   // Svalbard & Jan Mayen | 斯瓦尔巴岛和扬马延岛
	CC_SX     = 1721 // Sint Maarten | 圣马丁岛
	CC_CY     = 357  // Cyprus | 塞浦路斯
	CC_FI     = 358  // Finland | 芬兰
	CC_HR     = 385  // Croatia | 克罗地亚
	CC_MN     = 976  // Mongolia | 蒙古
	CC_WF     = 681  // Wallis & Futuna | 瓦利斯和富图纳
	CC_AD     = 376  // Andorra | 安道尔
	CC_EC     = 593  // Ecuador | 厄瓜多尔
	CC_GG     = 44   // Guernsey | 根西岛
	CC_MF     = 590  // St. Martin | 圣马丁
	CC_MZ     = 258  // Mozambique | 莫桑比克
	CC_PM     = 508  // St. Pierre & Miquelon | 圣皮埃尔和密克隆
	CC_UM     = 246  // U.S. Outlying Islands | 美国本土外小岛屿
	CC_AC     = 247  // Ascension Island | 阿森松岛
	CC_NG     = 234  // Nigeria | 尼日利亚
	CC_PF     = 689  // French Polynesia | 法属波利尼西亚
	CC_PW     = 680  // Palau | 帕劳
	CC_SN     = 221  // Senegal | 塞内加尔
	CC_SS     = 211  // South Sudan | 南非
	CC_GF     = 594  // French Guiana | 法属波利尼西亚
	CC_UG     = 256  // Uganda | 乌干达
	CC_BL     = 590  // St. Barthélemy | 圣巴泰勒米
	CC_GP     = 590  // Guadeloupe | 瓜德罗普
	CC_MU     = 230  // Mauritius | 毛里求斯
	CC_SG     = 65   // Singapore | 新加坡
	CC_SR     = 597  // Suriname | 苏里南
	CC_VE     = 58   // Venezuela | 委内瑞拉
	CC_KW     = 965  // Kuwait | 科威特
	CC_RW     = 250  // Rwanda | 卢旺达
	CC_BV     = 55   // Bouvet Island | 布韦岛
	CC_CC     = 61   // Cocos (Keeling) Islands | 科科斯（基林）群岛
	CC_CX     = 61   // Christmas Island | 圣诞岛
	CC_GN     = 224  // Guinea | 几内亚
	CC_HK     = 852  // Hong Kong SAR China | 香港
	CC_IC     = 34   // Canary Islands | 加那利群岛
	CC_IM     = 44   // Isle of Man | 马恩岛
	CC_ML     = 223  // Mali | 马里
	CC_NO     = 47   // Norway | 挪威
	CC_ZA     = 27   // South Africa | 南非
	CC_BI     = 257  // Burundi | 布隆迪
	CC_BZ     = 501  // Belize | 伯利兹
	CC_KZ     = 7    // Kazakhstan | 哈萨克斯坦
	CC_PH     = 63   // Philippines | 菲律宾
	CC_TF     = 262  // French Southern Territories | 法属波利尼西亚
	CC_TW     = 886  // Taiwan | 台湾
	CC_BM     = 1441 // Bermuda | 百慕大
	CC_EE     = 372  // Estonia | 爱沙尼亚
	CC_GD     = 1473 // Grenada | 格林纳达
	CC_NC     = 687  // New Caledonia | 新西兰
	CC_PK     = 92   // Pakistan | 巴基斯坦
	CC_SH     = 290  // St. Helena | 圣赫勒拿岛
	CC_AG     = 1268 // Antigua & Barbuda | 安提瓜和巴布达
	CC_BR     = 55   // Brazil | 巴西
	CC_ES     = 34   // Spain | 西班牙
	CC_FJ     = 679  // Fiji | 斐济
	CC_TG     = 228  // Togo | 多哥
	CC_SC     = 248  // Seychelles | 塞舌尔
	CC_AZ     = 994  // Azerbaijan | 阿塞拜疆
	CC_BG     = 359  // Bulgaria | 保加利亚
	CC_GW     = 245  // Guinea-Bissau | 几内亚比绍
	CC_KN     = 1869 // St. Kitts & Nevis | 圣基茨和尼维斯
	CC_MM     = 95   // Myanmar (Burma) | 缅甸
	CC_PE     = 51   // Peru | 秘鲁
	CC_IN     = 91   // India | 印度
	CC_MS     = 1664 // Montserrat | 蒙特塞拉特
	CC_SZ     = 268  // Swaziland | 斯威士兰
	CC_CN     = 86   // China | 中国
	CC_EG     = 20   // Egypt | 埃及
	CC_GS     = 500  // South Georgia And South Sandwich Islands | 南非
	CC_GY     = 592  // Guyana | 圭亚那
	CC_BD     = 880  // Bangladesh | 孟加拉国
	CC_CD     = 243  // Congo - Kinshasa | 刚果（金）
	CC_ZM     = 260  // Zambia | 赞比亚
	CC_BJ     = 229  // Benin | 贝宁
	CC_FO     = 298  // Faroe Islands | 法罗群岛
	CC_LA     = 856  // Laos | 老挝
	CC_MO     = 853  // Macau SAR China | 澳门
	CC_MW     = 265  // Malawi | 马拉维
	CC_VN     = 84   // Vietnam | 越南
	CC_AO     = 244  // Angola | 安哥拉
	CC_TN     = 216  // Tunisia | 突尼斯
	CC_TO     = 676  // Tonga | 汤加
	CC_CH     = 41   // Switzerland | 瑞士
	CC_DO     = 1809 // Dominican Republic | 多米尼加
	CC_GM     = 220  // Gambia | 冈比亚
	CC_MX     = 52   // Mexico | 墨西哥
	CC_NU     = 683  // Niue | 纽埃
	CC_SL     = 232  // Sierra Leone | 塞拉利
	CC_PT     = 351  // Portugal | 葡萄牙
	CC_VI     = 1340 // U.S. Virgin Islands | 美属维京群岛
	CC_CA     = 1    // Canada | 加拿大
	CC_ME     = 382  // Montenegro | 黑山
	CC_SO     = 252  // Somalia | 索马里
	CC_YE     = 967  // Yemen | 也门
	CC_DK     = 45   // Denmark | 丹麦
	CC_LC     = 1758 // St. Lucia | 圣卢西亚
	CC_LR     = 231  // Liberia | 利比里亚
	CC_MP     = 1670 // Northern Mariana Islands | 北马里亚纳
	CC_HU     = 36   // Hungary | 匈牙利
	CC_IR     = 98   // Iran | 伊朗
	CC_KG     = 996  // Kyrgyzstan | 吉尔吉斯斯坦
	CC_NL     = 31   // Netherlands | 荷属安的列斯
	CC_UA     = 380  // Ukraine | 乌克兰
	CC_AR     = 54   // Argentina | 阿根廷
	CC_BT     = 975  // Bhutan | 不丹
	CC_GR     = 30   // Greece | 希腊
	CC_AT     = 43   // Austria | 奥地利
	CC_CZ     = 420  // Czechia | 捷克
	CC_NR     = 674  // Nauru | 瑙鲁
	CC_PG     = 675  // Papua New Guinea | 巴布亚新几内亚
	CC_TT     = 1868 // Trinidad & Tobago | 特立尼达和多巴哥
	CC_CK     = 682  // Cook Islands | 库克群岛
	CC_DE     = 49   // Germany | 德国
	CC_KE     = 254  // Kenya | 肯尼亚
	CC_SI     = 386  // Slovenia | 斯洛文尼亚
	CC_IL     = 972  // Israel | 以色列
	CC_BH     = 973  // Bahrain | 巴林
	CC_BO     = 591  // Bolivia | 玻利维亚
	CC_MQ     = 596  // Martinique | 马提尼克
	CC_MR     = 222  // Mauritania | 毛里塔尼亚
	CC_US     = 1    // United States | 美国
	CC_AE     = 971  // United Arab Emirates | 阿联酋
	CC_MA     = 212  // Morocco | 摩洛哥
	CC_VG     = 1284 // British Virgin Islands | 英属维尔京群岛
	CC_BF     = 226  // Burkina Faso | 布基纳法索
	CC_GE     = 995  // Georgia | 格鲁吉亚
	CC_MC     = 377  // Monaco | 摩纳哥
	CC_RO     = 40   // Romania | 罗马尼亚
	CC_BW     = 267  // Botswana | 博茨瓦纳
	CC_SM     = 378  // San Marino | 圣马力诺
	CC_LT     = 370  // Lithuania | 立陶宛
	CC_PR     = 1787 // Puerto Rico | 波多黎各
	CC_ST     = 239  // São Tomé & Príncipe | 圣多美和普林西比
	CC_AI     = 1264 // Anguilla | 安圭拉
	CC_EH     = 212  // Western Sahara | 西撒哈拉
	CC_ID     = 62   // Indonesia | 印度尼西亚
	CC_VA     = 379  // Vatican City | 梵蒂冈
	CC_JM     = 1876 // Jamaica | 牙买加
	CC_NF     = 672  // Norfolk Island | 诺福克岛
)
